-- AlterTable: Add ACTIVE_BORROWER to CustomerStatus enum
ALTER TABLE `customers` 
  MODIFY COLUMN `status` ENUM('PROSPECT', 'REGISTERED', 'KYC_PENDING', 'KYC_VERIFIED', 'ELIGIBLE', 'ACTIVE_BORROWER', 'INELIGIBLE', 'BLACKLISTED') NOT NULL DEFAULT 'PROSPECT';
